name: nuget

on:
  workflow_dispatch:
  push:
    branches: "**"
  pull_request:
    branches: "**"

jobs:
  get_nuget:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: nuget/setup-nuget@v1
        with:
          nuget-version: 'latest'
      - uses: actions/cache@v1
        id: cache
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
      - name: NuGet Restore
        if: steps.cache.outputs.cache-hit != 'true'
        run: nuget restore gremy.ovh.sln --no-restore
